import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { DuneAdapter } from '../dune/adapter.js';
import { MemoryBanStore } from '../dune/banStore.js';
import { BanManager } from '../dune/bans.js';
import { Catalogue } from '../dune/catalogue.js';
import { loadConfig } from '../dune/config.js';
import { AmqpGmPublisher, GmClient, type ExecRunner } from '../dune/gm.js';
import { MemoryKnownPlayerStore } from '../dune/knownStore.js';
import { DunePg } from '../dune/pg.js';
import { DunePluginClient } from '../dune/pluginClient.js';
import { PluginJoin } from '../dune/pluginJoin.js';
import { DuneRmq } from '../dune/rmq.js';
import { MockBattlegroup, mockPlayer } from '../testing/mockBattlegroup.js';

/** Drops the `timestamp` some sources stamp on an event, so payload assertions stay readable. */
export function noTs(data: unknown): unknown {
  if (!data || typeof data !== 'object') return data;
  const { timestamp, ...rest } = data as Record<string, unknown>;
  void timestamp;
  return rest;
}

export const GM_TOKEN = 'test-server-command-token';

const FIXTURES = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'testing', 'fixtures');
export const FIXTURE_ITEMS = path.join(FIXTURES, 'items.json');
export const FIXTURE_ENTITIES = path.join(FIXTURES, 'entities.json');

export interface Harness {
  battlegroup: MockBattlegroup;
  adapter: DuneAdapter;
  pg: DunePg;
  rmq: DuneRmq;
  bans: BanManager;
  banStore: MemoryBanStore;
  catalogue: Catalogue;
  /** The inner GM payloads the adapter published, newest last. */
  gmSent: () => Record<string, unknown>[];
  execCalls: { argv: string[]; stdin: string }[];
}

export interface HarnessOptions {
  players?: ReturnType<typeof mockPlayer>[];
  plugin?: DunePluginClient | null;
  shutdownCmd?: string;
  shutdownNoticeSeconds?: number;
  /** Injected so the shutdown notice wait costs no real time in tests; records what was waited. */
  sleep?: (ms: number) => Promise<void>;
  execRunner?: ExecRunner;
  globalMessageMode?: 'chat' | 'broadcast' | 'both';
  /**
   * Exchanges the fake broker has declared. Pass a set without `chat.map` to reproduce a battlegroup whose map
   * process has not joined the broker (the state the rig was in at first boot) — `chat.map` is declared by the map
   * server, not by text-router.
   */
  exchanges?: string[];
  /** Override the catalogue files (default: the committed fixtures under `src/testing/fixtures/`). */
  itemsFile?: string;
  entitiesFile?: string;
  verifyWindowMs?: number;
  teleportVerifyWindowMs?: number;
  takaroRequestTimeoutMs?: number;
  takaroRequestMarginMs?: number;
  gmAuthToken?: string;
}

/** A whole connector wired to the in-memory battlegroup: no Postgres, no broker, no game. */
export async function harness(options: HarnessOptions = {}): Promise<Harness> {
  const battlegroup = new MockBattlegroup();
  battlegroup.players = options.players ?? [mockPlayer()];
  if (options.exchanges) battlegroup.exchanges = new Set(options.exchanges);

  const pg = new DunePg(battlegroup.db, { schema: 'dune', inventoryTypes: [0, 1, 14, 15, 27, 30] });
  await pg.probe();

  const config = loadConfig({});
  const rmq = new DuneRmq({
    url: 'amqps://test/',
    tlsInsecure: true,
    connect: battlegroup.connect,
    chatQueue: config.chatQueue,
    interceptExchange: config.chatInterceptExchange,
    interceptRoutingKey: config.chatInterceptRoutingKey,
    whisperExchange: config.whisperExchange,
    mapExchange: config.mapChatExchange,
    wire: config.chatWire,
    senderName: 'Takaro',
    announcerFuncomId: config.announcerFuncomId,
  });
  await rmq.start();

  const gm = new GmClient({
    authToken: options.gmAuthToken ?? GM_TOKEN,
    publisher: new AmqpGmPublisher(() => rmq.ensureChannel()),
    exchange: 'heartbeats',
    routingKey: 'notifications',
    userId: 'fls',
    appId: 'fls_backend',
  });

  // Committed fixtures, NOT `data/*.json`: the real catalogues are GENERATED by `npm run catalogue` (see
  // `data/SOURCES.md`), so a suite that read them would be testing whoever last ran the generator rather than the
  // connector, and would break the day the upstream wiki changes a name.
  const catalogue = new Catalogue({
    itemsFile: options.itemsFile ?? FIXTURE_ITEMS,
    entitiesFile: options.entitiesFile ?? FIXTURE_ENTITIES,
  });
  catalogue.load();

  const banStore = new MemoryBanStore();
  let adapter!: DuneAdapter;
  const bans = new BanManager({
    store: banStore,
    kick: async (gameId, reason) => (await adapter.kickPlayer({ gameId, reason })).verified === true,
    kickCooldownMs: 0,
  });

  adapter = new DuneAdapter({
    pg,
    gm,
    rmq,
    bans,
    catalogue,
    plugin: options.plugin ?? null,
    // The plugin knows Postgres row ids, not FLS ids, so every plugin-backed read goes through the
    // join — exactly as in production. A harness without a plugin gets no join either.
    pluginJoin: options.plugin
      ? new PluginJoin({
          players: () => options.plugin!.getPlayers(),
          roster: () => pg.roster({ limit: 100 }),
          ttlMs: 0,
        })
      : null,
    knownStore: new MemoryKnownPlayerStore(),
    senderName: 'Takaro',
    serverName: 'Takaro Dev Dune',
    gmPlayerIdKind: 'fls',
    globalMessageMode: options.globalMessageMode ?? 'chat',
    verifyWindowMs: options.verifyWindowMs ?? 100,
    teleportVerifyWindowMs: options.teleportVerifyWindowMs ?? 100,
    // 0 = "no Takaro budget known", so the existing tests keep their short windows untouched.
    takaroRequestTimeoutMs: options.takaroRequestTimeoutMs ?? 0,
    ...(options.takaroRequestMarginMs !== undefined ? { takaroRequestMarginMs: options.takaroRequestMarginMs } : {}),
    verifyIntervalMs: 20,
    shutdownCmd: options.shutdownCmd ?? '',
    ...(options.shutdownNoticeSeconds !== undefined ? { shutdownNoticeSeconds: options.shutdownNoticeSeconds } : {}),
    // Tests never burn real seconds on the shutdown countdown; the wait is asserted through this hook instead.
    sleep: options.sleep ?? (async () => {}),
    execRunner: options.execRunner,
  });

  return {
    battlegroup,
    adapter,
    pg,
    rmq,
    bans,
    banStore,
    catalogue,
    execCalls: battlegroup.execCalls,
    gmSent: () =>
      battlegroup.publishes
        .filter((p) => p.exchange === 'heartbeats')
        .map((p) => JSON.parse(JSON.parse(p.body).MessageContent) as Record<string, unknown>),
  };
}
