#!/usr/bin/env bash
# Dune: Awakening map-server entrypoint for the Takaro dev rig.
#
# Replaces Funcom's /home/dune/run.sh, which only works inside their k3s install:
# it asks the Kubernetes API for its node's ExternalIP, starts an sshd on
# gamePort-1111 and PATCHes its own pod annotations. Out here we supply the
# addresses ourselves and keep the process in the foreground so `docker stop`
# reaches it directly.
#
# Order of business:
#   1. writable Saved/ + UserSettings, and the symlink UE reads User*.ini through
#   2. render UserEngine.ini / UserGame.ini (GM gates, join password, DB DSN,
#      extended Allowed_GM_Commands)
#   3. work out the bind address (-MultiHome / -IGWBindAddress)
#   4. exec the game as uid 1000 with LD_PRELOAD set ONLY here, and only when the
#      Takaro plugin is actually present
set -euo pipefail

log() { printf '[takaro-entrypoint] %s\n' "$*"; }

ROOT="${DUNE_SERVER_ROOT:-/home/dune/server}"
SAVED="${ROOT}/DuneSandbox/Saved"
US="${SAVED}/UserSettings"
BIN_REL="DuneSandbox/Binaries/Linux/DuneSandboxServer-Linux-Shipping"
EPIC_CFG="/home/dune/.config/Epic/Unreal Engine/Engine/Config"

[ -s "${ROOT}/${BIN_REL}" ] || { log "FATAL: ${ROOT}/${BIN_REL} is missing — wrong base image?"; exit 1; }

# ── 1. writable state ───────────────────────────────────────────────────────
mkdir -p "$US" "${SAVED}/Logs" "${SAVED}/DatabaseDumps"
if [ "$(id -u)" = "0" ]; then
    # The bind mount arrives owned by whoever created it; the game runs as `dune`
    # (uid 1000, gid 65534) and rewrites its own config on shutdown.
    chown -R dune:nogroup "$SAVED" 2>/dev/null || log "warning: could not chown ${SAVED} (read-only mount?)"
fi

mkdir -p "$(dirname "$EPIC_CFG")"
if [ -d "$EPIC_CFG" ] && [ ! -L "$EPIC_CFG" ]; then rm -rf "$EPIC_CFG"; fi
ln -sfn "$US" "$EPIC_CFG"
log "UE user config: ${EPIC_CFG} -> ${US}"

# ── 2. config overrides ─────────────────────────────────────────────────────
# UE reads, last to win: Base*.ini -> Default*.ini -> DedicatedServer*.ini ->
# the User*.ini in the Epic config dir we just symlinked. Secrets live in these
# files (mode 600, owner dune) rather than on the command line, so they stay out
# of `ps`, `docker inspect` and the container log. Set DUNE_INI_VIA_ARGS=1 to pass
# them as -ini: arguments instead, if a build ever ignores the file route.
ini_esc() { printf '%s' "${1//\"/}"; }

want_ini_file=1
[ "${DUNE_INI_VIA_ARGS:-0}" = "1" ] && want_ini_file=0

USER_ENGINE="${US}/UserEngine.ini"
USER_GAME="${US}/UserGame.ini"

{
    printf '; generated by takaro-entrypoint.sh — hand edits are overwritten on every boot\n'
    printf '[URL]\n'
    printf 'Port=%s\n' "${DUNE_GAME_PORT:-7777}"
    printf 'IGWPort=%s\n\n' "${DUNE_IGW_PORT:-7888}"

    printf '[ConsoleVariables]\n'
    # The GM command seam. Without this cvar the NotificationSystem never reads the
    # heartbeats exchange and every server command is silently dropped.
    printf 'server.NotificationSystem.Enabled=%s\n' "${DUNE_NOTIFICATION_SYSTEM_ENABLED:-1}"
    [ -n "${DUNE_SERVER_DISPLAY_NAME:-}" ] && printf 'Bgd.ServerDisplayName="%s"\n' "$(ini_esc "$DUNE_SERVER_DISPLAY_NAME")"
    [ -n "${DUNE_SERVER_LOGIN_PASSWORD:-}" ] && printf 'Bgd.ServerLoginPassword="%s"\n' "$(ini_esc "$DUNE_SERVER_LOGIN_PASSWORD")"
    printf '\n'

    printf '[FuncomLiveServices]\n'
    printf 'DefaultFlsEnvironment=%s\n' "${DUNE_FLS_ENV:-retail}"
    if [ "$want_ini_file" = "1" ]; then
        # ServerCommandsAuthToken appears in NO Funcom-authored config file; the literal
        # only exists in the binary. This is the lever that authenticates GM commands.
        [ -n "${DUNE_GM_AUTH_TOKEN:-}" ] && printf 'ServerCommandsAuthToken=%s\n' "$DUNE_GM_AUTH_TOKEN"
        [ -n "${DUNE_FLS_SECRET:-}" ] && printf 'ServiceAuthToken=%s\n' "$DUNE_FLS_SECRET"
    fi
    printf '\n[OnlineSubsystem]\n'
    [ -n "${WORLD_UNIQUE_NAME:-}" ] && printf 'ServerName=%s\n' "$WORLD_UNIQUE_NAME"
    [ -n "${DUNE_DATACENTER_ID:-}" ] && printf 'DatacenterId=%s\n' "$DUNE_DATACENTER_ID"
} > "$USER_ENGINE"

{
    printf '; generated by takaro-entrypoint.sh — hand edits are overwritten on every boot\n'
    printf '[AdminSetting.Global]\n'
    # DedicatedServerGame.ini ships an Allowed_GM_Commands list WITHOUT KickPlayer,
    # ServiceBroadcast or AwardXP. They are real commands (the names are in the binary),
    # so without this append three Takaro actions fail for a config reason that looks
    # exactly like a wire bug. `+Key=` appends to the array the earlier files built.
    IFS=',' read -r -a extra <<< "${DUNE_EXTRA_GM_COMMANDS:-}"
    for c in "${extra[@]}"; do
        c="${c//[[:space:]]/}"
        [ -n "$c" ] && printf '+Allowed_GM_Commands=%s\n' "$c"
    done
    printf '\n'
    if [ "$want_ini_file" = "1" ] && [ -n "${DUNE_DB_HOST:-}" ]; then
        printf '[DuneDatabaseInterfacePSQL]\n'
        printf 'DatabaseHost=%s\n' "$DUNE_DB_HOST"
        printf 'DatabaseName=%s\n' "${DUNE_DB_NAME:?DUNE_DB_NAME is required when DUNE_DB_HOST is set}"
        printf 'DatabaseUser=%s\n' "${DUNE_DB_USER:-dune}"
        printf 'DatabasePassword=%s\n' "${DUNE_DB_PASSWORD:-}"
        printf 'DatabaseConnectTimeout=%s\n' "${DUNE_DB_TIMEOUT:-15}"
    fi
} > "$USER_GAME"

if [ -n "${DUNE_CUSTOM_SETTINGS_FILE:-}" ] && [ -r "${DUNE_CUSTOM_SETTINGS_FILE}" ]; then
    cp -f "${DUNE_CUSTOM_SETTINGS_FILE}" "${US}/UserServerCustomSettings.ini"
    log "copied UserServerCustomSettings.ini from ${DUNE_CUSTOM_SETTINGS_FILE}"
fi

chmod 600 "$USER_ENGINE" "$USER_GAME" 2>/dev/null || true
if [ "$(id -u)" = "0" ]; then chown dune:nogroup "$USER_ENGINE" "$USER_GAME" 2>/dev/null || true; fi
log "rendered UserEngine.ini + UserGame.ini (secrets withheld from the log)"

# BattlEye: DefaultEngine.ini ships BattlEye.Enabled=false. Assert it, loudly, because
# the plugin lane must never LD_PRELOAD into a process with an anti-cheat module live.
if grep -qi '^BattlEye.Enabled=false' "${ROOT}/DuneSandbox/Config/DefaultEngine.ini" 2>/dev/null; then
    log "BattlEye.Enabled=false in DefaultEngine.ini (as shipped)"
else
    log "WARNING: could not confirm BattlEye.Enabled=false — do NOT preload the plugin"
fi

# ── 3. addresses ────────────────────────────────────────────────────────────
BIND_IP="${DUNE_BIND_IP:-$(hostname -i 2>/dev/null | awk '{print $1}')}"
[ -n "$BIND_IP" ] || { log "FATAL: could not determine the container IP for -MultiHome"; exit 1; }
EXTERNAL_ADDRESS="${EXTERNAL_ADDRESS:-$BIND_IP}"
log "bind=${BIND_IP} external=${EXTERNAL_ADDRESS} game=${DUNE_GAME_PORT}/udp igw=${DUNE_IGW_PORT}/udp"

# ── 4. launch ───────────────────────────────────────────────────────────────
PRELOAD=""
if [ -n "${TAKARO_PLUGIN_SO:-}" ]; then
    if [ -s "${TAKARO_PLUGIN_SO}" ]; then
        PRELOAD="${TAKARO_PLUGIN_SO}"
        log "LD_PRELOAD=${PRELOAD}"
    else
        # An LD_PRELOAD pointing at a missing or empty file fails the whole exec.
        log "TAKARO_PLUGIN_SO=${TAKARO_PLUGIN_SO} is missing or empty — starting WITHOUT the plugin"
    fi
else
    log "no Takaro plugin requested (TAKARO_PLUGIN_SO unset)"
fi

set -- "${ROOT}/${BIN_REL}" DuneSandbox \
    -Port="${DUNE_GAME_PORT:-7777}" \
    -IGWPort="${DUNE_IGW_PORT:-7888}" \
    -MultiHome="${BIND_IP}" \
    -IGWBindAddress="${BIND_IP}" \
    -ExternalAddress="${EXTERNAL_ADDRESS}" \
    -PartitionIndex="${DUNE_PARTITION_INDEX:-1}" \
    -FarmRegion="${DUNE_FARM_REGION:-Europe}" \
    -RMQGameTlsEnabled="${DUNE_RMQ_TLS_ENABLED:-true}" \
    --RMQGameHostname="${DUNE_RMQ_GAME_HOST:-game-rmq}" \
    --RMQGamePort="${DUNE_RMQ_GAME_PORT:-5672}" \
    --RMQAdminHostname="${DUNE_RMQ_ADMIN_HOST:-admin-rmq}" \
    --RMQAdminPort="${DUNE_RMQ_ADMIN_PORT:-5672}" \
    -nocrashreports -unattended -log

if [ "${DUNE_INI_VIA_ARGS:-0}" = "1" ]; then
    # Fallback route: identical settings, but visible in `ps`. Only for debugging a
    # build that ignores the User*.ini files.
    set -- "$@" \
        "-ini:engine:[ConsoleVariables]:server.NotificationSystem.Enabled=${DUNE_NOTIFICATION_SYSTEM_ENABLED:-1}" \
        "-ini:engine:[FuncomLiveServices]:ServerCommandsAuthToken=${DUNE_GM_AUTH_TOKEN:-}" \
        "-ini:engine:[FuncomLiveServices]:ServiceAuthToken=${DUNE_FLS_SECRET:-}" \
        "-ini:game:[DuneDatabaseInterfacePSQL]:DatabaseHost=${DUNE_DB_HOST:-}" \
        "-ini:game:[DuneDatabaseInterfacePSQL]:DatabaseName=${DUNE_DB_NAME:-}" \
        "-ini:game:[DuneDatabaseInterfacePSQL]:DatabaseUser=${DUNE_DB_USER:-dune}" \
        "-ini:game:[DuneDatabaseInterfacePSQL]:DatabasePassword=${DUNE_DB_PASSWORD:-}"
fi

# shellcheck disable=SC2086  # DUNE_EXTRA_ARGS is intentionally word-split
set -- "$@" ${DUNE_EXTRA_ARGS:-}

cd "$ROOT"
log "exec (argv redacted where it carries secrets): ${1} DuneSandbox -Port=${DUNE_GAME_PORT} -IGWPort=${DUNE_IGW_PORT} -MultiHome=${BIND_IP} -ExternalAddress=${EXTERNAL_ADDRESS} -PartitionIndex=${DUNE_PARTITION_INDEX} ..."

# exec => the game is PID 1 and gets SIGTERM from `docker stop` itself. Funcom's
# run.sh needed a trap because it backgrounded the process through `su`.
if [ "$(id -u)" = "0" ]; then
    exec setpriv --reuid=dune --regid=nogroup --clear-groups \
        env HOME=/home/dune LD_PRELOAD="${PRELOAD}" "$@"
else
    exec env LD_PRELOAD="${PRELOAD}" "$@"
fi
